[package]
name = "rs-sqlite"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Pszczółkowski"]
about = "rust wrapper for access to sqlite3 library"

[dependencies]
libc = "0.2.140"
sqlite3-sys = "0.14.0"
chrono = "0.4.24"
fxhash = "0.2.1"